name: GenerateDocs

# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#on
on:
  push:
    branches:
      - main

# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobs
jobs:
  gen_docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: jiro4989/setup-nim-action@v1
      - name: Pull kaushalmodi's global config.nims
        run: nim pullConfig
      - name: Generate docs
        run: nim docs

# https://github.com/nim-lang/Nim/wiki/BuildServices#github-actions
# https://docs.github.com/en/actions/learn-github-actions/introduction-to-github-actions
