name: RunTests

on:
  pull_request:
    types:
      - '*'
  push:
  schedule:
    # Every week: https://crontab.guru/#0_0_*_*_0
    - cron: '0 0 * * 0'

jobs:
  run_tests:
    # runs-on: ubuntu-latest
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: jiro4989/setup-nim-action@v1
      - name: Pull kaushalmodi's global config.nims
        run: nim pullConfig
      - name: Run tests
        run: nim test
